### PR TITLE
feat: added/deleted files, changed functions, added new functions

### PR DESCRIPTION
**Pull request by Nelshulla**

### CODE REVIEW

**Review by Moibrahi7 — APPROVED** [review]
LGTM

**Comment by anthonydmays** [comment]
Lol, wut???

**Comment by Nelshulla** [comment]
> Lol, wut???

Is there a problem in the code?

**Comment by anthonydmays** [comment]
> > Lol, wut???
> 
> Is there a problem in the code?

Sorry, I was reacting to the PR title and description. It looks like you were doing some refactoring, but you didn't describe what you were changing and why.

**Comment by Nelshulla** [comment]
> > > Lol, wut???
> > 
> > 
> > Is there a problem in the code?
> 
> Sorry, I was reacting to the PR title and description. It looks like you were doing some refactoring, but you didn't describe what you were changing and why.

Ohh yeah, I had so many files that I worked on for different things, that I forgot to write a description. I really just wanna be done with the project, I'm burnt out.

**Comment by anthonydmays** [comment]
> > > > Lol, wut???
> > > 
> > > 
> > > Is there a problem in the code?
> > 
> > 
> > Sorry, I was reacting to the PR title and description. It looks like you were doing some refactoring, but you didn't describe what you were changing and why.
> 
> Ohh yeah, I had so many files that I worked on for different things, that I forgot to write a description. I really just wanna be done with the project, I'm burnt out.

Sometimes it be like that! Well, you're almost to the finish line...

**Pull request merged**
